</head>
<body onunload="return JSPostNotification('ShouldExitPage', this);">

<div id="loading">Loading...</div>
<div id="message-container"></div>
<div id="error-container"></div>

<div id="frame">
<div id="content-frame">

<div id="container">
<div id="logo"><img alt="Hydra Control Freak" src="/hcf/images/hcf.jpg" onclick="location.assign('/hcf');"></div>
<div id="top-header">
	
	<img alt="Hydra Control Freak" src="/hcf/images/hcf-title.jpg">
	
	<div id="head-bar">
		<div class="button status" onclick="location.assign('/hcf/systemstatus');">System Status</div>
		<div class="button status" onclick="location.assign('/hcf/systemlog');">System Log</div>
		<div class="button status" onclick="location.assign('/hcf/rfxcomlog');">RFXCOM Log</div>
		<div class="button status" onclick="location.assign('/hcf/phidgetlog');">Phidget Log</div>
		<div class="button status" onclick="location.assign('/hcf/actionlog');">Action Log</div>
		<div class="button status" onclick="location.assign('/hcf/formatlog');">Format Log</div>
	</div>
	
	<div class="hr" style="padding-top:10px;"></div>
</div>

<div id="main">

<div id="menus">

<div id="mm_home" class="menu-header" onclick="location.assign('/hcf/');">Home</div>
<div id="mm_actions" class="menu-header" onclick="location.assign('/hcf/actions');">Actions</div>
<div id="mm_schedules" class="menu-header" onclick="location.assign('/hcf/schedules');">Scheduled Actions</div>
<div id="mm_profiles" class="menu-header" onclick="location.assign('/hcf/profiles');">Profiles</div>
<div id="mm_buttongroups" class="menu-header" onclick="location.assign('/hcf/buttongroups');">Button Groups</div>

<div id="mm_cameras" class="menu-header" onclick="location.assign('/hcf/cameras');">Cameras</div>
<div id="mm_rfxcom" class="menu-header" onclick="location.assign('/hcf/rfxcom');">RFXCOM</div>
<div id="mm_phidgets" class="menu-header" onclick="location.assign('/hcf/phidgets');">Phidgets</div>
<div id="mm_freaks" class="menu-header" onclick="location.assign('/hcf/freaks');">Linked Freaks</div>

<div id="mm_synthetics" class="menu-header" onclick="location.assign('/hcf/synthetics');">Combination Events</div>
<div id="mm_watchdogs" class="menu-header" onclick="location.assign('/hcf/watchdogs');">Watchdogs</div>


<div id="mm_email" class="menu-header" onclick="location.assign('/hcf/email');">E-mail</div>

<div id="mm_maintenance" class="menu-header" onclick="location.assign('/hcf/maintenance');">Maintenance</div>
<div id="mm_system" class="menu-header" onclick="location.assign('/hcf/system');">System</div>
<div id="mm_users" class="menu-header" onclick="location.assign('/hcf/users');">Users</div>
<div id="mm_links" class="menu-header" onclick="location.assign('/hcf/links');">Links</div>

</div>

<script type="text/javascript">
	/**
		This script should be above all other scripts.
	*/
	
	// set to "false" to suppress console messages generated by the configuration
	Debug = true;
</script>

<div id="content">
